### ISSUE TITLE
When i use angular universal i get this error

### ISSUE THREAD

**Issue by Pahanbl4** [ddubrava/angular8-yandex-maps#62]
TypeError: Cannot read property 'geoObjects' of undefined
    at YaPlacemarkComponent.../node_modules/angular8-yandex-maps/__ivy_ngcc__/bundles/angular8-yandex-maps.umd.js.YaPlacemarkComponent.ngOnDestroy (E:\Shop-online\dist\viewer\server\main.js:171213:23)
    at executeOnDestroys (E:\Shop-online\dist\viewer\server\main.js:75718:32)
    at cleanUpView (E:\Shop-online\dist\viewer\server\main.js:75640:13)
    at destroyViewTree (E:\Shop-online\dist\viewer\server\main.js:75435:51)
    at destroyLView (E:\Shop-online\dist\viewer\server\main.js:75593:13)
    at RootViewRef.../node_modules/@angular/core/__ivy_ngcc__/bundles/core.umd.js.ViewRef.destroy (E:\Shop-online\dist\viewer\server\main.js:76335:13)
    at E:\Shop-online\dist\viewer\server\main.js:95296:71
    at Array.forEach (<anonymous>)
    at ApplicationRef.../node_modules/@angular/core/__ivy_ngcc__/bundles/core.umd.js.ApplicationRef.ngOnDestroy (E:\Shop-online\dist\viewer\server\main.js:95296:33)

**Comment by ddubrava** [comment]
Angular/Library version?

**Comment by Pahanbl4** [comment]
![image](https://user-images.githubusercontent.com/22370107/105612710-aeaab000-5dce-11eb-99f2-d91a8d54581e.png)

**Comment by ddubrava** [comment]
The bug was fixed in `10.4.1` - https://github.com/ddubrava/angular8-yandex-maps/issues/43.

You can try to upgrade to `"angular8-yandex-maps": "^10.4.0"` or `"angular8-yandex-maps": "^11.0.0"`, it should work with Angular 9. If not, please let me know, I'll fix the bug in 9 version.

**Comment by Pahanbl4** [comment]
Thank you so much. After updating to 10.4.1 it worked.
